// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWProject;

#nullable disable

namespace SW.DAL.Migrations
{
    [DbContext(typeof(SWContext))]
    [Migration("20220209125615_AddedCascadeDeleting")]
    partial class AddedCascadeDeleting
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SWProject.Base", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AmmoSupplyId")
                        .HasColumnType("int");

                    b.Property<int?>("AttachedFleetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AmmoSupplyId");

                    b.HasIndex("AttachedFleetId");

                    b.ToTable("Base");
                });

            modelBuilder.Entity("SWProject.BaseFleet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("Fleets");
                });

            modelBuilder.Entity("SWProject.Clone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BaseId")
                        .HasColumnType("int");

                    b.Property<string>("Equipment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LegionId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StarshipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseId");

                    b.HasIndex("LegionId");

                    b.HasIndex("StarshipId");

                    b.ToTable("Clones");
                });

            modelBuilder.Entity("SWProject.Droid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BaseId")
                        .HasColumnType("int");

                    b.Property<string>("Equipment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StarshipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseId");

                    b.HasIndex("StarshipId");

                    b.ToTable("Droid");
                });

            modelBuilder.Entity("SWProject.Jedi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("LegionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PadawanId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PadawanId")
                        .IsUnique()
                        .HasFilter("[PadawanId] IS NOT NULL");

                    b.ToTable("Jedies");
                });

            modelBuilder.Entity("SWProject.Legion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("GeneralJediId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GeneralJediId")
                        .IsUnique()
                        .HasFilter("[GeneralJediId] IS NOT NULL");

                    b.ToTable("Legions");
                });

            modelBuilder.Entity("SWProject.Starship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("FleetId")
                        .HasColumnType("int");

                    b.Property<string>("PathList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WeaponryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FleetId");

                    b.HasIndex("WeaponryId");

                    b.ToTable("Starships");
                });

            modelBuilder.Entity("SWProject.StarshipWeaponry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("LaserDoubleCannonCnt")
                        .HasColumnType("int");

                    b.Property<int>("LaserTargetDefenseCannonCnt")
                        .HasColumnType("int");

                    b.Property<int>("LaserTurretCnt")
                        .HasColumnType("int");

                    b.Property<int>("ProtonTorpedoLauncherCnt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StarshipWeaponries");
                });

            modelBuilder.Entity("SWProject.Supply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CartridgesCnt")
                        .HasColumnType("int");

                    b.Property<int>("FuelCnt")
                        .HasColumnType("int");

                    b.Property<int>("GrenadesCnt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Supplies");
                });

            modelBuilder.Entity("SWProject.Base", b =>
                {
                    b.HasOne("SWProject.Supply", "AmmoSupply")
                        .WithMany()
                        .HasForeignKey("AmmoSupplyId");

                    b.HasOne("SWProject.BaseFleet", "AttachedFleet")
                        .WithMany("AttachedBases")
                        .HasForeignKey("AttachedFleetId");

                    b.Navigation("AmmoSupply");

                    b.Navigation("AttachedFleet");
                });

            modelBuilder.Entity("SWProject.Clone", b =>
                {
                    b.HasOne("SWProject.Base", "Base")
                        .WithMany("Clones")
                        .HasForeignKey("BaseId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("SWProject.Legion", "Legion")
                        .WithMany("Clones")
                        .HasForeignKey("LegionId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("SWProject.Starship", "Starship")
                        .WithMany("Passangers")
                        .HasForeignKey("StarshipId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Base");

                    b.Navigation("Legion");

                    b.Navigation("Starship");
                });

            modelBuilder.Entity("SWProject.Droid", b =>
                {
                    b.HasOne("SWProject.Base", "Base")
                        .WithMany("Droids")
                        .HasForeignKey("BaseId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("SWProject.Starship", "Starship")
                        .WithMany("Droids")
                        .HasForeignKey("StarshipId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Base");

                    b.Navigation("Starship");
                });

            modelBuilder.Entity("SWProject.Jedi", b =>
                {
                    b.HasOne("SWProject.Jedi", "Padawan")
                        .WithOne("Teacher")
                        .HasForeignKey("SWProject.Jedi", "PadawanId");

                    b.Navigation("Padawan");
                });

            modelBuilder.Entity("SWProject.Legion", b =>
                {
                    b.HasOne("SWProject.Jedi", "GeneralJedi")
                        .WithOne("Legion")
                        .HasForeignKey("SWProject.Legion", "GeneralJediId");

                    b.Navigation("GeneralJedi");
                });

            modelBuilder.Entity("SWProject.Starship", b =>
                {
                    b.HasOne("SWProject.BaseFleet", "Fleet")
                        .WithMany("Starships")
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("SWProject.StarshipWeaponry", "Weaponry")
                        .WithMany()
                        .HasForeignKey("WeaponryId");

                    b.Navigation("Fleet");

                    b.Navigation("Weaponry");
                });

            modelBuilder.Entity("SWProject.Base", b =>
                {
                    b.Navigation("Clones");

                    b.Navigation("Droids");
                });

            modelBuilder.Entity("SWProject.BaseFleet", b =>
                {
                    b.Navigation("AttachedBases");

                    b.Navigation("Starships");
                });

            modelBuilder.Entity("SWProject.Jedi", b =>
                {
                    b.Navigation("Legion");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SWProject.Legion", b =>
                {
                    b.Navigation("Clones");
                });

            modelBuilder.Entity("SWProject.Starship", b =>
                {
                    b.Navigation("Droids");

                    b.Navigation("Passangers");
                });
#pragma warning restore 612, 618
        }
    }
}
